name: Execute Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        ODOO_URL: ${{ vars.ODOO_URL }}
        ODOO_DB: ${{ vars.ODOO_DB }}
        ODOO_USER: ${{ vars.ODOO_USER }}
        ODOO_PASS: ${{ secrets.ODOO_PASS }}
      run: |
        python -m unittest discover
